PR : 실습 1주차 세미나 필수과제
DO-SOPT-ANDROID/kwanhee-jo pull request #1
Opened 2023-10-08 14:54 UTC by Jokwanhee

### 개요 🐢
기초적인 UI 학습

### 상세 설명
- **로그인**
- **회원가입**
- **마이페이지(메인)**

### 추가 내용
- **BaseXXX 추상 클래스 사용**
ViewBinding 변수와 onCreate 함수에서의 binding 초기화를 추상클래스를 만들어서 사용했습니다!  SnackBar 호출하는 것도 해당 클래스에서 메서드로 만들어봤습니다.
- **Parcelize**
Parcelize 플러그인을 사용해서 Parcelable를 구현하는 데이터 클래스를 만들어봤습니다. intent를 사용할 때, putExtra 로 데이터 클래스 객체와 같은 꾸러미의 데이터를 넘겨주기 위해서 사용해봤습니다!
- **커스텀 뷰 사용**
반복되는 TextView와 EditText를 한 번에 사용하기 위해서 커스텀 뷰를 사용했습니다! 재사용성이 있어 다음에 똑같은 UI를 사용하게 된다면 유용하다고 생각했습니돠!
- **Enum class 사용**
열거형 클래스를 사용해서 MBTI를 나타내봤습니다. 

### 영상
https://github.com/DO-SOPT-ANDROID/kwanhee-jo/assets/90740783/e2667e81-6005-4fad-99ec-dcb6bc10afa7

2023-10-10 04:17 UTC, Marchbreeze reviewed
미쳤다 이 남자

2023-10-10 04:17 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
모든 액티비티에서 initView()와 initEvent()를 override 할 필요가 없다면, 꼭 baseActivity에서 다뤄야 하는 부분인지 궁금합니다!

2023-10-10 04:17 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/SignUpActivity.kt
> +        password.length in 8..12
int 값들을 parameter로 max와 min을 받는다면 ID와 PW를 체크하는 함수를 하나로 다뤄서 중복을 줄일 수 있을 것 같아요 ~~
저는 
```kotlin
    private fun checkLength(text: String, min: Int, max: Int): Boolean =
        text.length in min..max
``` 
처럼 작성했던 것 같아요

2023-10-10 04:17 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/view/SoptEditView.kt
> +class SoptEditView @JvmOverloads constructor(
커스텀뷰 폼 미쳤네요 ...

2023-10-10 04:31 UTC, KwakEuiJin requested changes
Base와 커스텀 뷰까지 활용하신거 너무 인상깊었습니다!! 고생 많으셨습니다. 리뷰 확인 후 수정해주시면 approve하겠습니다.

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
사용하지 않을수도 있는 함수를 abstract으로 선언해서 결합력을 높이는 것 보다 다른 방법을 사용해보는 것이 어떨까요??

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    }
상속 대신 확장함수를 이용하면 View에 접근이 가능한 곳애서 활용가능하기에 더욱 확장성있는 개발이 될 것 같습니다.

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
abstract class를 언제 활용해야하는지 추가적으로 조사해보시면 좋을 것 같아요~!! 🌟

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +        }
1. resultActivity 라는 변수명은 조금 모호한 것 같아요! 조금 더 기능을 잘 나타내는 변수명으로 교체하면 좋을 것 같습니다.
2. getParcelableExtra는 Util or 확장함수로 빼서 사용하면 재사용성이 증가할 것 같습니다

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +    }
오 이런식으로 동적으로 할당할 수도 있군요 잘 배워갑니다!

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +                }
지속적으로 "user" 키가 반복되는데 상수로 분리 후 재사용하는 것이 어떨까요?

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +        binding.btLogin.setOnClickListener {
initEvent()를 각 관심사별로 분리하는 게 가독성상 좋아보입니다!
제가 code With me애서 보여드렸던 방식처럼 한번 분리해보시면 좋을 것 같습니다

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="4:4"
4:4 면 1:1 로 -> 1 도 가능 할 것 같습니다~!!

2023-10-10 04:31 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/view/SoptEditView.kt
> +    var editHint: String? = null
혹시 Title과 Hint를 전역 가변변수로 선언한 이유가 있을까요??

2023-10-10 04:48 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +                }
보내는 액티비티에
```kotlin
companion object {
        const val EXTRA_USER = "user"
    }
``` 
처럼 상수화해두고, 받는 액티비티에 해당 액티비티의 상수를 import 받아서 활용한다면 추후에 상수를 수정해야하는 경우에 한번에 수정이 가능합니다~~

2023-10-10 04:55 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
요 부분은 제 습관 중 하나이긴 합니다... 
지금은 initView를 거의 사용하지 않지만, 확장성을 생각해서 나중에 사용하지 않을까!!? 하면서 만들게 되었습니다!
지금 보니 필요없는 함수가 만들어져서 Code Smell 이네요..😥

2023-10-10 05:02 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/SignUpActivity.kt
> +        password.length in 8..12
오! 꿀팁 감사합니다! 바로 적용해봐야겠습니다! 
commit : [2ca29f3](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/2ca29f38dbc8f68682fd3517a782188e7c5f4b0c)

2023-10-10 05:21 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
abstract fun이어도, 안에 꼭 상속해야할 내용물이 없는 함수라면 불필요한 코드가 액티비티마다 생성될 수 있을 것 같은 우려가 됩니닷..ㅎㅎ 또한 initEvent와 같은 함수는 무거운 액티비티로 커지는 경우 event마다 다른 함수들로 기능별로 쪼개주는게 유지보수 측면에서 더 용이할 듯 해요 ~~

2023-10-10 05:39 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    abstract fun initEvent()
> 사용하지 않을수도 있는 함수를 abstract으로 선언해서 결합력을 높이는 것 보다 다른 방법을 사용해보는 것이 어떨까요??

다른 방법이 뭐가 있을까요..? 리펙터링 해야할 부분이라고 생각은 했지만, 직접 어떻게 구현해야할 지 모르겠습니다 ㅠㅠ 인터페이스를 잘 활용하면 될까라는 생각도 했지만... 모르겠네요...

2023-10-10 05:44 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +    }
확장함수를 이용하니 훨씬 코틀린스러운 코드가 된 것 같습니다! 자바와 다르게 함수형 프로그래밍의 장점을 더욱 부각하는것 같아서 잘 배워갑니다!
commit : [c4fb689](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/c4fb6899fb91f11013738cfce190ff24983eaa45)

2023-10-10 06:04 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +        }
1. ㅎㅎ.. 저도 다시보니 변수이름이 왜저러나 싶네요
2. 확장함수로 빼서 사용하니깐 코드가 엄청많이 줄었어요! 감사합니다!

commit : [836466a](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/836466aa4fe022056312d879ad7c77e5898cbcf9)

2023-10-10 06:07 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +                }
오 상수를 정의하면서 나중에 헷갈리지 않을 수 있을 것 같아요! 실수를 방지하는 좋은 방법 감사드립니다!
commit : [de3af00](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/de3af00bd14560479d25d5fa3eb758e37f6fdbe2)

2023-10-10 06:21 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/LoginActivity.kt
> +        binding.btLogin.setOnClickListener {
세미나 1주차에서 잘 알려줘가지고 쉽게 관심사를 분리해볼 수 있었습니다~ 변수명이나 함수명은 아직 너무너무 어렵네요 ㅠ
commit : [c3dc8dc](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/c3dc8dc9b7766965a2d620ba21c8e6d6123d04c6)

2023-10-10 06:27 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/view/SoptEditView.kt
> +    var editHint: String? = null
확장성을 고려한 변수 설정입니다. 현재는 xml 에서 수정하지만, 동적으로 할당하기 위한 방법을 고려해서 변수를 선언 및 할당해놓았습니다. 즉, xml 선언 방법과 동적 할당 방법을 모두 고려해서 가변변수로 선언하였습니다!

2023-10-10 06:28 UTC, Jokwanhee commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="4:4"
... 왜 4:4 라고 했을까 생각이 되는 코드네요..
commit : [ff8695a](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/1/commits/ff8695a9961aa61c9e7a6b72cd7e5e405fc16c71)

2023-10-10 23:08 UTC, KwakEuiJin approved these changes
수정 확인했습니다~!! 고생하셨어요

2023-10-11 07:18 UTC, Jokwanhee commented
> 수정 확인했습니다~!! 고생하셨어요

리뷰 감사요~!

2023-10-13 05:26 UTC, yeonjeen reviewed
처음 보는 코드들도 많고, 다양하게 구현하신 부분들도 많아서 굉장히 흥미롭게 봤습니다!!

2023-10-13 05:26 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +abstract class BaseActivity<T : ViewBinding>(val bindingFactory: (LayoutInflater) -> T) :
다른 분들 코드에서도 자주 보였는데 BaseActivity를 만드는 이유는 뭔가요??

2023-10-13 05:26 UTC, yeonjeen commented on app/src/main/res/values/strings.xml
> +    <string name="profile_description">저는 스쿼트를 좋아하는데요? 어쩌라구요</string>
개취 확인했습니다 ㅋㅋ

2023-10-13 11:11 UTC, emjayMJkim reviewed
코드 멋있네요 보고 배워갑니다..!!

2023-10-13 11:11 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/SignUpActivity.kt
> +    private fun isSuccessMBTI(mbti: MBTI): Boolean =
조건별로 따로따로 함수화해줘서 더 깔끔한 것 같네요~!!

2023-10-13 11:11 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/view/SoptEditView.kt
> +class SoptEditView @JvmOverloads constructor(
이야.. 커스텀뷰 멋있네요

2023-10-13 11:11 UTC, emjayMJkim commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintVertical_chainStyle="packed" />
혹시 chainStyle로 설정한 이유가 뭔가요? 그냥 단순 궁금증입니다 ㅎㅎ

2023-10-13 13:42 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseActivity.kt
> +abstract class BaseActivity<T : ViewBinding>(val bindingFactory: (LayoutInflater) -> T) :
추상 클래스입니다. 액티비티를 계속해서 만들면 중복되는 코드가 많아져요! 그래서 이 추상 클래스를 부모 클래스라고 생각하면 자식들에게 부모의 덕을 자식들에게 넘겨줍니다. 그 덕이 중복을 없애주는 덕이에요! 그래서 자식 클래스 즉, 로그인 액티비티, 회원가입 액티비티에서 구현해야할 중복되는 코드를 작성하게 됩니다!

2023-10-13 13:43 UTC, Jokwanhee commented on app/src/main/res/values/strings.xml
> +    <string name="profile_description">저는 스쿼트를 좋아하는데요? 어쩌라구요</string>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 스쿼트 같이 하실래요?

2023-10-13 13:44 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/SignUpActivity.kt
> +    private fun isSuccessMBTI(mbti: MBTI): Boolean =
감사합니다! 세미나에서 Code With me 를 통해서 얻어가는 이점을 적용해보네요 .. :)

2023-10-13 13:45 UTC, Jokwanhee commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintVertical_chainStyle="packed" />
로그인 버튼이랑 회원가입 버튼이 멀어지는 게 싫어서 pack chain style 로 붙였습니다 ㅎ_ㅎ

2023-10-14 19:30 UTC, merged