PR : 실습 4주차 필수과제
DO-SOPT-ANDROID/kwanhee-jo pull request #13
Opened 2023-11-12 12:18 UTC by Jokwanhee

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #12 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- Retrofit2 with MVVM 패턴+ Repository 패턴 적용
- Application 사용으로 retrofit 및 sharedPreference 초기화
- HttpLogginInterceptor 및 OkHttpClient 사용 
- 회원가입 및 로그인 API 연동
- Reqres List Users API 연동

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/DO-SOPT-ANDROID/kwanhee-jo/assets/90740783/84eb768e-42df-4e4f-8149-1baedd71db8f

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
Retrofit 과 함께 MVVM + Repository 패턴을 적용해보았습니다. 의존성 주입을 위한 라이브러리를 사용하지 않고 하니 뭔가 코드가 복잡해보입니다. ViewModelFactory, Application 등 클래스, 인터페이스가 많아지니깐 어지럽네요..  제대로 패턴이 적용된지도 모르겠네요... 리뷰 항상 감사드립니다! (채찍질 부탁드립니다.. 지적할 부분있으면 달게 받겠습니다!)

2023-11-17 06:53 UTC, KwakEuiJin requested changes
전체적으로 주석제거 및 코멘트 확인 한번 부탁드립니다~!! 너무 고생하셨어요 👍

2023-11-17 06:53 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/db/remote/AuthApiHelper.kt
> +                        onResponse(SignUpResp.Success(response.headers()["Location"]?.split("/")?.last().toString()))
isSuccessful변수가 true라는 것은 200번대라는 얘기이기 때문에 code까지 분기해서 확인할 필요는 없으실 것 같습니다~!!

2023-11-17 06:53 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/db/remote/AuthApiHelper.kt
> +                    t.printStackTrace()
t.printStackTrace의 경우에는 에러로그가 릴리즈 상황에서도 보이기 때문에 Log를 활용하여 erro를 찍는 것을 권장드립니다!

2023-11-17 06:53 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeActivity.kt
>      }
👏

2023-11-17 06:53 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +            ).get(LoginViewModel::class.java)
initView함수에 initViewModel이 있는게 조금 이상하네요~!! ViewModel을 생성하는 시점이 언제여야하는지 함수의 관심사 분리와 함께 고민해보시면 좋을 것 같습니다.

2023-11-17 06:53 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +    }
Base가 initView를 강제하다보니 이렇게 되는 것 같은데 Base구조 변경을 고려하여야할 것 같습니다

2023-11-17 06:53 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +    }
함수명이 어떤 동작을 하는지 잘 모르겠어요! if문도 너무 길어서 가독성이 떨어지는 것 같습니다

2023-11-17 06:53 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/repository/AuthRepository.kt
> +}
authApiHelper에서 signUp과 login이 suspend 함수가 아닌데 해당 키워드를 붙여주신 이유가 있을까요??

2023-11-17 14:03 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/repository/AuthRepository.kt
> +}
코루틴 공부한다고 해놓고 제가 안지웠네요.. 지우고 나중에 코루틴 공부하면서 적용하겠습니당!

2023-11-17 14:14 UTC, Jokwanhee commented
> 전체적으로 주석제거 및 코멘트 확인 한번 부탁드립니다~!! 너무 고생하셨어요 👍

코드 리뷰 해주셔서 감사합니다 _ _) 리뷰에 대한 피드백 적용해보았습니다 📃

2023-11-19 07:27 UTC, KwakEuiJin approved these changes
굳굳!! 🍀

2023-11-19 11:36 UTC, emjayMJkim reviewed
과제 하느라 수고했어~~ 멋있다 진짜

2023-11-19 11:36 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/model/dto/req/LoginReq.kt
> +data class LoginReq(
혹시 Request 끝까지 안 써주는 이유가 따로 있을까요..?? LoginReqrest 이런 식으로 쓰는 게 더 가독성이 좋을 것 같아서염..!!

2023-11-19 11:36 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +            ).get(SignUpViewModel::class.java)
굳굳

2023-11-19 14:35 UTC, yeonjeen reviewed
코드를 보면서 가독성도 좋고 코드도 간결해서 이해가 잘 되었던 것 같아요!! 항상 많이 배우고갑니다!!

2023-11-19 14:35 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/db/remote/AuthApiHelper.kt
> +}
callback 부분이 코드가 비슷한데 이럴 때 함수화를 시켜도 될까요?

2023-11-19 14:35 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +        && binding.soptEvMbti.getEditText().toMBTI() != MBTI.ERROR
이 부분 함수보면서 가독성이 정말 좋다고 느꼈어요!!

2023-11-20 02:10 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/db/remote/AuthApiHelper.kt
> +}
해당 부분의 반복되는 코드를 줄이기 위해서 확장함수로 사용하는 방법은 우리 안드 파트장님이 꿀팁 공유에 "우리 5인큐 하자" 라는 타이틀의 아티클을 올렸으니 한 번 확인해보면 좋을 듯 합니다!!

2023-11-20 02:11 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/model/dto/req/LoginReq.kt
> +data class LoginReq(
저는 Req = Request 인데, 다른분들이 보기에는 헷갈릴수도있겠네용.. 이번에 서버통신할 때 풀네임으로 함수네임 만들어보겠씁니다!

2023-11-20 02:13 UTC, merged