PR : 실습 2주차 과제
DO-SOPT-ANDROID/kwanhee-jo pull request #6
Opened 2023-10-19 06:55 UTC by Jokwanhee

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- #5 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- **바텀 네비게이션**
안드로이드, 홈, 마이페이지

- **리사이클러뷰 구현**
멀티 뷰 타입 지원  (sealed class 사용)
^ 헤더 : 나의 프로필 (리스트 맨 처음에 추가)
^ 콘텐트 : 생일인 친구 (친구 중 생일을 체크하여 자료구조 큐를 사용하여 첫 번째 인덱스에 차례로 추가)
^ 홈 : 친구   
 
- **업데이트 추가**
데이터 스키마에 update 파라미터를 추가하여 하루 이내에 갱신된 내용이 있으면 프로필 이미지 왼쪽상단에 표시

- **제약조건을 활용한 elipsize 설정하기**
constriantLayout 적극 활용하여 프로필 이름, 상태 메시지, 상태 바에 대응하여 글자 컨텐츠 마지막 ... 표현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/kwanhee-jo/assets/90740783/cc364637-47bd-4540-a47e-3a1c8dd6ff47

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
이번 과제는 구현은 잘 된 것 같은데, 설계할 때 고민을 많이했습니다..
더더더더더 잘할 수 있을 것 같은데, 뭔가 아쉬운 부분이 많아요 ㅠ (코드를 더 간소화할 수 있지 않을까?)
리뷰 부탁드립니다! 👍

2023-10-19 08:57 UTC, librarywon reviewed
멀티뷰타입 미쳤다 그냥 와우

2023-10-19 09:06 UTC, Marchbreeze reviewed
너무 잘하셔서... 코드리뷰 달만한게 없네요.... 미쳤다 이남자

2023-10-19 09:06 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +        notifyDataSetChanged()
요 친구 아래에 밑줄 그어지는거 거슬리시지 않나요? ㅎㅎ 심화과제에서 ListAdapter를 활용한다면 밑줄 없이 깔끔하게 진행하실 수 있습니닷 ~

2023-10-19 09:06 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeContentsViewHolder.kt
> +                .transform(MultiTransformation(CenterCrop(), RoundedCorners(50)))
Glide 라이브러리 활용 너무 좋네요 !! 다만 요즘은 대세가 [Coil 라이브러리](https://velog.io/@jojo_devstory/Android-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%A1%9C%EB%94%A9-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-Coil-%EC%9D%84-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90) 활용으로 넘어가는 추세라 요 라이브러리에 대해서도 한번 알아보면 좋을 것 같아요 ㅎㅎ

2023-10-19 09:06 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeActivity.kt
> +    }
요 친구들을 따로 함수화해둔 이유가 있나요?

2023-10-19 09:06 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +        testDeque.apply {
임시리스트로 담아둔 코드들을 따로 파일에 리스트로 저장해두고, Fragment 파일에서는 해당 리스트를 받아와서 활용하는 방식을 사용하신다면 더 깔끔하고 유지보수가 용이한 코드를 작성하실 수 있을 것 같습니다 ~

2023-10-19 11:09 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +        notifyDataSetChanged()
ListAdapter쓰면 아이템 사이즈 함수도 없어지지롱

2023-10-19 11:11 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeContentsViewHolder.kt
> +                .transform(MultiTransformation(CenterCrop(), RoundedCorners(50)))
이건 원으로 잘라주는 친구인가보군요 글라이드 많이 안써봐서 진짜 모름

2023-10-19 11:13 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +        testDeque.apply {
뷰모델을 사용한다면 더 깔끔한코드가 될 것 같네요

2023-10-19 11:13 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            binding.tvIdContent.text = this?.getString(ID, "") ?: return@with
`?: return@with` 이 문법은 뭔가요?

2023-10-19 11:14 UTC, librarywon commented on app/src/main/res/drawable/jokwanhee.jpg
잘생기기까지 했다 이 남자

2023-10-19 11:14 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintVertical_bias="0.9" />
아마 실수로 들어갔을 듯 싶은데 지워주세요!

2023-10-19 11:15 UTC, librarywon commented on app/src/main/res/layout/item_profile_contents.xml
> +        android:background="@drawable/bg_ffffff_stroke_dd4f4f_2_corners_50"
오우...파일명 보소

2023-10-19 11:17 UTC, haeti-dev reviewed
오비분들이 코리를 많이 달아주시겠지만, 정말 좋은 코드들이 많네요. 자꾸 이러면.. 과제를 어렵게 내야하나.. ㅎ 
고생하셨습니다 최고최고 👍

2023-10-19 11:17 UTC, haeti-dev commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +            )
뷰타입을 Sealed Class를 활용해서 사용해봅시당

2023-10-19 14:49 UTC, KwakEuiJin requested changes
정말 빠르게 과제를 하셨군요!! 역시 👍 리뷰 확인 및 수정 부탁드립니다~!!

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeHeaderViewHolder.kt
> +        }
Glide 반복되는 로직이 많은데 확장이나 Util로 분리하면 좋을 것 같습니다~!!

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/model/HomeProfileModel.kt
> +sealed class HomeProfileModel
어떠한 의도로 모델파일들을 분리해놓으셨나요?!

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            }
scope함수의 용도를 살짝 공부해보면 좋을 것 같습니다, apply는 주로 초기화 및 객체반환시 사용되며, 참조를 위해서 사용하시는거라면, run을 쓰는게 더 좋을 것 같네요

2023-10-19 14:49 UTC, KwakEuiJin commented on app/build.gradle
>      compileOptions {
이번 과제에 dataBinding을 적용하신 이유가 있을까요??

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +        notifyDataSetChanged()
👍

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/model/Profile.kt
> +}
모델 내에서 이런식으로 간단한 계산 처리하는 거 너무 좋은 것 같아요

2023-10-19 14:49 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            binding.tvIdContent.text = this?.getString(ID, "") ?: return@with
```suggestion
        activity?.getSharedPreferenceUser()?.run {
            binding.tvIdContent.text = this?.getString(ID, "")
```

2023-10-19 14:53 UTC, librarywon commented on app/build.gradle
>      compileOptions {
이게 의진이 눈에 들어와버렸네

2023-10-20 01:07 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +        notifyDataSetChanged()
오잉.. 거슬렸는데 빨리 도전과제하면서 ListAdapter 사용해야겠네요!

2023-10-20 01:10 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeContentsViewHolder.kt
> +                .transform(MultiTransformation(CenterCrop(), RoundedCorners(50)))
Coil.. 이 녀석도 한 번 사용해봐야겠네요!

2023-10-20 01:15 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeActivity.kt
> +    }
initView는 액티비티 추상클래스의 추상함수여서 구현부를 따로 작성해야하는데.. 프래그먼트를 붙이는 구현부를 또 따로 함수로 빼볼까 하면서 함수를 만들었습니다. 따로 이유는 없습니다! 🤣

2023-10-20 01:16 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeContentsViewHolder.kt
> +                .transform(MultiTransformation(CenterCrop(), RoundedCorners(50)))
맞습니당! 👋

2023-10-20 01:17 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            binding.tvIdContent.text = this?.getString(ID, "") ?: return@with
엘비스 연산자를 사용해서 널일 때, with 스코프 함수를 나가게 만들었습니다.

2023-10-20 01:18 UTC, Jokwanhee commented on app/src/main/res/drawable/jokwanhee.jpg
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 🤣 감사합니다!

2023-10-20 01:19 UTC, Jokwanhee commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintVertical_bias="0.9" />
요거 constraint 제약을 걸어서 오른쪽 하단에 로그아웃 버튼을 해둔건데 없애면 왼쪽 상단으로 이동합니다. 혹시 지워야할 부분이 다른 부분인가요!?

2023-10-20 02:09 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/model/HomeProfileModel.kt
> +sealed class HomeProfileModel
리스트의 타입을 하나로 묶기 위해서 사용했습니다. 리스트를 받고 각 요소들이 어떤 데이터 클래스를 가지는 가에 따라서 viewType을 다르게 반환하게 진행했습니다.
```kotlin
private var profileList = emptyList<HomeProfileModel>()
```
```kotlin
override fun getItemViewType(position: Int): Int {
     return when (profileList[position]) {
         is ProfileHeader -> HomeViewTypeModel.Header.type
         is ProfileBirthday -> HomeViewTypeModel.Birthday.type
         is Profile -> HomeViewTypeModel.Profile.type
     }
}
```

2023-10-20 02:14 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            }
@KwakEuiJin 엇! 반대 아닌가요? "apply ~ 객체 반환시 사용" 이라는 말이 어떤 의미인건가요?

2023-10-20 02:16 UTC, Jokwanhee commented on app/build.gradle
>      compileOptions {
BaseFragment 를 만들기 위해서 DataBindingUtil 클래스를 사용하기 위해서 데이터 바인딩을 사용했습니다.. 뷰 바인딩 으로 view를 인플레이트하기 위해서는 여러 인자가 필요해서 기존 `::inflate` 를 사용하는 방법으로는 해결되지 않아.. 굳이 필요없는 데이터 바인딩이 사용하게 되었습니다!

2023-10-20 02:19 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            binding.tvIdContent.text = this?.getString(ID, "") ?: return@with
[ef09303](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/ef0930311c9f41c2a5e99f76ffcbbe74df780710)

오.. 감사합니다. 저도 불편한 코드였는데 깔끔하네요!

2023-10-20 02:19 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeAdapter.kt
> +            )
[b196360](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/b196360d9ca3c38669d01e8ec081937ebe077230)

멀티 뷰 타입을 사용해봤습니다! 훨씬 확장성 있게 작성된 것 같아요!

2023-10-20 02:20 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +        testDeque.apply {
@Marchbreeze 
[daef0fe](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/daef0fe350fa326460d21c6628e2427133dee64c)

임시 리스트 파일을 만들어서 접근하니 훨씬 코드의 양이 적어지네요! 따로 분리하는 샘플 자료를 만든다는 것 굉장히 좋은 것 같습니다. 감사합니다~!

2023-10-20 03:59 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeHeaderViewHolder.kt
> +        }
[4b45cfc](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/4b45cfcc24893fe125137020fdaa9f50eac93847)

확장함수 사용하니 거의 12줄의 코드가 2줄로 줄었습니다! 가독성 측면에서 매우 좋은 것 같습니다 감사합니다 _ _)

2023-10-20 04:40 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            }
``` kotlin
val intent = Intent().apply {
    putExtra("key", value)
}
```

apply는 이런식으로 Intent 자체를 반환하기에 해당 객체를 초기화 하는 용도로 자주 사용됩니다.

2023-10-20 04:41 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/model/HomeProfileModel.kt
> +sealed class HomeProfileModel
음 제 질문의 의도는 왜 sealed class HomeProfileModel {
블럭 내에서 data class를 정의하지 않고 분리하셨는지 궁금했습니다!
}

2023-10-20 04:42 UTC, KwakEuiJin commented on app/build.gradle
>      compileOptions {
오히려 데이터 바인딩이 layoutId가 필요하여 더 많은 인자가 필요하지 않나요?!! (단순 궁금)

2023-10-20 05:08 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintVertical_bias="0.9" />
`layout_constraintVertical_bias` 이 코드가 필요한 상태인가요?

2023-10-20 06:08 UTC, Jokwanhee commented on app/build.gradle
>      compileOptions {
아 제가 말을 잘못했네요.. 말씀이 맞습니다!

2023-10-20 06:09 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/model/HomeProfileModel.kt
> +sealed class HomeProfileModel
아.. 고건 제가 수정해야했는데, 수정을 안했네요.. 원래 sealed 클래스를 정의하지 않고 데이터 클래스를 먼저 정의하면서 시작해서 수정해야했는데 까먹고 있었습니다..ㅎ_ㅎ 수정할게요!

2023-10-20 06:24 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +            }
와 진짜 몰랐어요.. 스코프를 제대로 알고 사용한 것이 아니였다는 제 자신이 부끄럽네요.. 또 배워갑니다 갓의진!!!!
[444cada](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/444cada1c5c9ae439cf6436483f26e29c36a4e53)

2023-10-20 06:35 UTC, Jokwanhee commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintVertical_bias="0.9" />
저는 로그아웃 버튼을 더 오른쪽 하단에 깔리게 하기위해서 bias를 주었습니다! 근데 지금 보니깐 딱히 필요없어 보이네요.. 하.. 제가 원래 어렸을 때 그림을 참 못그렸는 데 여기서 또 이러네요; 감사합니다 💛 
[39f5e5f](https://github.com/DO-SOPT-ANDROID/kwanhee-jo/pull/6/commits/39f5e5fe30f0e19da24dc626ec5676aacd3d8834)

2023-10-27 14:12 UTC, KwakEuiJin approved these changes

2023-10-29 04:57 UTC, emjayMJkim reviewed
코드 진짜 멋있습니다.. 잘 보고 갑니당

2023-10-29 04:57 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeViewHolder.kt
> +            binding.tvStatusMessage.visibility = View.GONE
이 부분 XML에서 처리해줄 수도 있습니다!!

2023-10-29 04:57 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/model/HomeProfileModel.kt
> +            System.currentTimeMillis() - update <= (1000 * 60 * 60 * 24)
멋있습니다..!

2023-10-29 12:29 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeViewHolder.kt
> +            binding.tvStatusMessage.visibility = View.GONE
@emjayMJkim 
헉.. 어떻게 하면 할 수 있는거죠? 데이터바인딩을 사용하는 부분인건가요!?

2023-10-30 10:57 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeViewHolder.kt
> +            binding.tvStatusMessage.visibility = View.GONE
넵 맞습니당~ (그냥 또 하나의 방법일 뿐입니다...ㅎㅎ)

2023-11-02 05:18 UTC, yeonjeen reviewed
항상 과제 1등!! 멋있어요!! 수고하셨습니다~

2023-11-02 05:18 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeViewHolder.kt
> +            binding.ivUser.roundedCornerGlide(binding.root, item.profileImage, 150, 50)
roundedCornerGlide를 사용하는 큰 이점이 뭘까요?

2023-11-02 05:18 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/MyPageFragment.kt
> +class MyPageFragment : BaseFragment<FragmentMypageBinding>() {
관희님 코드 보면서 BaseFragment/BaseActivity가 있다는 걸 알았어요!! 많이 배우고 갑니다

2023-11-02 05:18 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/util/SampleList.kt
> +            Music("노래 제목이 길게하면 어떨까?", "박효신")
박효신 엄청 좋아하시네요 ㅋㅋ

2023-11-02 07:05 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/adapter/HomeViewHolder.kt
> +            binding.ivUser.roundedCornerGlide(binding.root, item.profileImage, 150, 50)
확장함수를 사용한 함수입니다! 코틀린은 자바와 다르게 최상위 함수를 가집니다. 자바는 클래스로 묶어서 다니죠.. 재사용성이랑 코드의 가독성측면이라는 이점이 있다고 생각합니다. 추가로 코틀린스러운 코드라고 생각합니당

2023-11-06 16:30 UTC, merged